### ISSUE TITLE
Implement conditions for all LICs

### ISSUE THREAD

**Issue by osclind** [martinfalke/dd2480-g18-decide#79]
We need to implement input checks for LICs. David takes LIC1, LIC8, LIC13, see issues #76, #77 and #78, respectively.

**Comment by osclind** [comment]
I will take LICs 0, 2, 3, 4, 5, 6

**Comment by LukasGutenberg** [comment]
we need tests for invalid data for LICs 0, 2 3 4 5 6. I will fix it
